title: The Balagan blog
author: balagan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the Balagan blog, where you will learn about all manner of strange and bizzare things
# social links
twitter_username: balagangadol # DO NOT include the @ character, or else the build will fail!
github_username:  balagangadol # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
